# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "oryol-build"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "puppet"

  # use NFS shared folder because they are much faster
  # then VBox shared folders, a bit more hassle to setup 
  # though (asks for the host machine's root password, 
  # and doesn't work on Windows)
  config.vm.network "private_network", ip: "192.168.127.127"
  config.vm.synced_folder "../../oryol", "/home/vagrant/oryol", type: "nfs"
end
