# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "oryol-linux"
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "puppet"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # use NFS shared folder because they are much faster
  # then VBox shared folders, a bit more hassle to setup 
  # though (asks for the host machine's root password, 
  # and doesn't work on Windows)
  # MEH, this is still all very slow, better to clone
  # a new copy into the VM's local FS instead of sharing
  # config.vm.network "private_network", ip: "192.168.127.127"
  # config.vm.synced_folder "../../oryol", "/home/vagrant/oryol", type: "nfs"
end
